============================= test session starts =============================
platform win32 -- Python 3.11.0, pytest-8.1.1, pluggy-1.5.0
rootdir: D:\PROJETOS\SISTEMAS\PROGRAMAS\omni_keywords_finder
configfile: pytest.ini
plugins: anyio-4.9.0, Faker-24.14.1, asyncio-0.26.0, cov-4.1.0
asyncio: mode=Mode.STRICT, asyncio_default_fixture_loop_scope=None, asyncio_default_test_loop_scope=function
collected 1 item

tests\integration\api\test_import_app.py .                               [100%]

============================== warnings summary ===============================
C:\Users\SEDUC\Desktop\PROJETOS\omni_keywords_finder\.venv\Lib\site-packages\_pytest\config\__init__.py:1439
  C:\Users\SEDUC\Desktop\PROJETOS\omni_keywords_finder\.venv\Lib\site-packages\_pytest\config\__init__.py:1439: PytestConfigWarning: Unknown config option: timeout
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================== 1 passed, 1 warning in 10.47s ========================
